/**
 * Paystack API helpers
 *
 * IMPORTANT — amounts are always in KOBO (KES × 100).
 *   KES 1,000  →  amount_kobo: 100_000
 *   KES 5,500  →  amount_kobo: 550_000
 *
 * All fetch calls have a 10-second timeout via AbortSignal.timeout().
 */

const PAYSTACK_BASE = "https://api.paystack.co";

function getSecretKey(): string {
  const key = process.env.PAYSTACK_SECRET_KEY;
  if (!key) throw new Error("Missing required environment variable: PAYSTACK_SECRET_KEY");
  return key;
}

// ---------------------------------------------------------------------------
// Shared fetch helper
// ---------------------------------------------------------------------------

async function paystackFetch<T>(
  path: string,
  options: RequestInit = {}
): Promise<T> {
  const res = await fetch(`${PAYSTACK_BASE}${path}`, {
    ...options,
    signal: AbortSignal.timeout(10_000),
    headers: {
      Authorization: `Bearer ${getSecretKey()}`,
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });

  const body = (await res.json()) as { status: boolean; message: string; data: T };

  if (!res.ok || !body.status) {
    throw new Error(
      `Paystack error [${res.status}] on ${path}: ${body.message ?? "Unknown error"}`
    );
  }

  return body.data;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface InitializePaymentParams {
  /** Customer email address */
  email: string;
  /**
   * Amount in KOBO (KES × 100).
   * e.g. KES 1,500 → 150_000
   */
  amount_kobo: number;
  /** Unique transaction reference generated by the caller */
  reference: string;
  /** Arbitrary key-value data attached to the transaction */
  metadata?: Record<string, unknown>;
}

export interface InitializePaymentResult {
  /** Paystack-hosted checkout URL — redirect the user here */
  authorization_url: string;
  /** Access code for the transaction (alternative to URL) */
  access_code: string;
  /** The reference echoed back from Paystack */
  reference: string;
}

export interface PaystackTransactionData {
  id: number;
  status: "success" | "failed" | "abandoned";
  reference: string;
  amount: number; // in kobo
  currency: string;
  paid_at: string | null;
  created_at: string;
  channel: string;
  customer: {
    id: number;
    email: string;
    name: string | null;
  };
  metadata: Record<string, unknown> | null;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Create a new Paystack transaction and return the checkout URL.
 *
 * @example
 * const { authorization_url, reference } = await initializePayment({
 *   email: "customer@example.com",
 *   amount_kobo: 350_000,   // KES 3,500
 *   reference: "hkh_1234_abc",
 *   metadata: { bookingId: "uuid-here" },
 * });
 */
export async function initializePayment(
  params: InitializePaymentParams
): Promise<InitializePaymentResult> {
  return paystackFetch<InitializePaymentResult>(
    "/transaction/initialize",
    {
      method: "POST",
      body: JSON.stringify({
        email: params.email,
        amount: params.amount_kobo,
        reference: params.reference,
        currency: "KES",
        callback_url: `${process.env.NEXT_PUBLIC_APP_URL ?? "https://hookah-website-two.vercel.app"}/booking/confirm`,
        ...(params.metadata ? { metadata: params.metadata } : {}),
      }),
    }
  );
}

/**
 * Verify a transaction by reference. Call after redirect from Paystack or
 * in the webhook handler.
 *
 * @throws if the HTTP request fails or Paystack returns status=false
 * @returns Raw transaction data — check `.status === "success"` yourself.
 */
export async function verifyPayment(
  reference: string
): Promise<PaystackTransactionData> {
  return paystackFetch<PaystackTransactionData>(
    `/transaction/verify/${encodeURIComponent(reference)}`
  );
}
